### ISSUE TITLE
Properly handle error message for expired credentials

### ISSUE THREAD

**Issue by marco-hoyer** [marco-hoyer/cfn-sphere#3]
If one uses cfg-sphere with expired credentials, it stops with ugly log message:

(cfn-sphere-venv)foo:infrastructure foo$ cf sync test.yml
24.08.2015 17:40:23 ERROR connection: 403 Forbidden
24.08.2015 17:40:23 ERROR connection: <ErrorResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
  <Error>
    <Type>Sender</Type>
    <Code>ExpiredToken</Code>
    <Message>The security token included in the request is expired</Message>
  </Error>
  <RequestId>6f2db1a4-4a76-11e5-a422-e51fd6279686</RequestId>
</ErrorResponse>

Traceback (most recent call last):
  File "/data/home/mhoyer/cfn-sphere-venv/bin/cf", line 69, in <module>
    cli()
  File "/data/home/mhoyer/cfn-sphere-venv/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/data/home/mhoyer/cfn-sphere-venv/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/data/home/mhoyer/cfn-sphere-venv/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/data/home/mhoyer/cfn-sphere-venv/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/home/mhoyer/cfn-sphere-venv/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/data/home/mhoyer/cfn-sphere-venv/bin/cf", line 41, in sync
    get_current_account_alias()), abort=True):
  File "/data/home/mhoyer/cfn-sphere-venv/bin/cf", line 16, in get_current_account_alias
    return boto.connect_iam().get_account_alias().account_aliases[0]
  File "/data/home/mhoyer/cfn-sphere-venv/lib/python2.7/site-packages/boto/iam/connection.py", line 1019, in get_account_alias
    list_marker='AccountAliases')
  File "/data/home/mhoyer/cfn-sphere-venv/lib/python2.7/site-packages/boto/iam/connection.py", line 102, in get_response
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.BotoServerError: BotoServerError: 403 Forbidden
<ErrorResponse xmlns="https://iam.amazonaws.com/doc/2010-05-08/">
  <Error>
    <Type>Sender</Type>
    <Code>ExpiredToken</Code>
    <Message>The security token included in the request is expired</Message>
  </Error>
  <RequestId>6f2db1a4-4a76-11e5-a422-e51fd6279686</RequestId>
</ErrorResponse>

**Comment by marco-hoyer** [comment]
done
